package com.zhumeiyuan.codingagent.agent.tool;

public enum ToolExecutionErrorCode {
	UNKNOWN_TOOL,
	INVALID_ARGUMENTS,
	WORKSPACE_NOT_FOUND,
	WORKSPACE_INVALID_PATH,
	WORKSPACE_PERMISSION_DENIED,
	WORKSPACE_ACCESS_DENIED,
	WORKSPACE_CONFLICT,
	WORKSPACE_EDIT_MISS,
	TOOL_RUNTIME_ERROR,
	TOOL_TIMEOUT
}
