package com.zhumeiyuan.codingagent.agent.workspace;

public enum WorkspaceAccessCode {
	BLANK_PATH,
	ABSOLUTE_PATH,
	PATH_ESCAPE,
	SENSITIVE_PATH,
	NOT_FOUND,
	NOT_DIRECTORY,
	NOT_REGULAR_FILE,
	INVALID_WRITE_TARGET,
	PARENT_NOT_FOUND,
	PARENT_NOT_DIRECTORY,
	SYMLINK_ESCAPE,
	FILE_TOO_LARGE,
	INVALID_TEXT,
	FILE_ALREADY_EXISTS,
	CONTENT_CONFLICT,
	TEXT_NOT_FOUND,
	IO_ERROR
}
